library(dplyr)
print(myLevels)
factor(myTable$Industry)
myTable$Industry <- as.character(myTable$Industry)
class(myTable$Industry)
techMVB <- filter(myTable, myTable$Industry == "Technology")
luxMVB <- filter(myTable, myTable$Industry == "Luxury")
AutoMVB <- filter(myTable, myTable$Industry == "Automotive")
finServMVB <- filter(myTable, myTable$Industry == "Financial Services")
